# 模型配置
model:
  name: "HNet"
  in_channels: 1
  out_channels: 1
  features: 8
  num_levels: 1

# 数据配置
data:
  train_path: "data/train/"
  val_path: "data/val/"
  test_path: "data/test"
  batch_size: 4
  num_workers: 4
  pin_memory: true

# 训练配置
training:
  epochs: 300
  learning_rate: 0.0003
  weight_decay: 0.0001
  early_stopping_patience: 20
  use_amp: true
  gradient_clip: 1.0

# 优化器配置
optimizer:
  type: "AdamW"
  betas: [0.9, 0.999]
  eps: 1e-08
  amsgrad: false

# 模型保存配置
model_save:
  path: "model/HNet.pth"
  save_best_only: true

# 设备配置
device:
  use_cuda: true

# 预测配置
predict:
  output_dir: "prediction/"